name: nix
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Nix
        uses: cachix/install-nix-action@v22
      - name: Build with Nix
        run: |
          nix develop -c cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja
          nix develop -c cmake --build build
